app/views/field_view.py
from flask import Blueprint, request, redirect, render_template, url_for, current_app
from flask_wtf import FlaskForm
from wtforms import fields
from wtforms.fields import html5

field_view_bp = Blueprint('field_view', __name__)

class StringForm(FlaskForm):
    name = fields.StringField('name')

@field_view_bp.route('/string', methods=('GET', 'POST'))
def string():
    form = StringForm()
    if form.validate_on_submit():
        return render_template('field/string.html', form=form, success=True)
    return render_template('field/string.html', form=form)


class BasicForm(FlaskForm):
    boolean = fields.BooleanField('boolean')
    date = fields.DateField('date')
    date_time = fields.DateTimeField('date_time')
    decimal = fields.DecimalField('decimal')
    file = fields.FileField('file')
    multiple_file = fields.MultipleFileField('multiple_file')
    float = fields.FloatField('float')
    integer = fields.IntegerField('integer')
    radio = fields.RadioField('radio', choices=['a', 'b', 'c'])
    #DOTO: Select fields with dynamic choice values
    select = fields.SelectField('select', choices=[('cpp', 'C++'), ('py', 'Python'), ('text', 'Plain Text')])
    select_multiple = fields.SelectMultipleField('select_multiple', choices=[('cpp', 'C++'), ('py', 'Python'), ('text', 'Plain Text')])
    string = fields.StringField('string')
    hidden = fields.HiddenField('hidden')
    password = fields.PasswordField('password')
    text_area = fields.TextAreaField('text_area')

    search = html5.SearchField('search')
    tel = html5.TelField('tel')
    url = html5.URLField('url')
    email = html5.EmailField('email')
    html5_date_time = html5.DateTimeField('html5_date_time')
    html5_date = html5.DateField('html5_date')
    time = html5.TimeField('time')
    date_time_local = html5.DateTimeLocalField('date_time_local')
    html5_integer = html5.IntegerField('html5_integer')
    html5_decimal = html5.DecimalField('html5_decimal')
    integer_range = html5.IntegerRangeField('integer_range')
    decimal_range = html5.DecimalRangeField('decimal_range')
    

    submit = fields.SubmitField('Submit')

@field_view_bp.route('/basic', methods=('GET', 'POST'))
def basic():
    form = BasicForm()

    if request.method == 'POST' and form.validate_on_submit():
        return render_template('field/basic.html', form=form, success=True)

    return render_template('field/basic.html', form=form)

app/templates/field/basic.html
<hr>
{% from "base/_render_field.html" import render_field %}

<form method="POST" action="{{ url_for('field_view.basic') }}">
    {{ form.csrf_token }}
    {{ render_field(form.boolean) }}
    {{ render_field(form.date) }}
    {{ render_field(form.date_time) }}
    {{ render_field(form.decimal) }}
    {{ render_field(form.file) }}
    {{ render_field(form.multiple_file) }}
    {{ render_field(form.float) }}
    {{ render_field(form.integer) }}
    {{ render_field(form.radio) }}
    {{ render_field(form.select) }}
    {{ render_field(form.select_multiple) }}
    {{ render_field(form.hidden) }}
    {{ render_field(form.password) }}
    {{ render_field(form.text_area) }}
    html5 -----------------------------------------<br/>
    {{ render_field(form.search) }}
    {{ render_field(form.tel) }}
    {{ render_field(form.url) }}
    {{ render_field(form.email) }}
    {{ render_field(form.html5_date_time) }}
    {{ render_field(form.html5_date) }}
    {{ render_field(form.time) }}
    {{ render_field(form.date_time_local) }}
    {{ render_field(form.html5_integer) }}
    {{ render_field(form.html5_decimal) }}
    {{ render_field(form.integer_range) }}
    {{ render_field(form.decimal_range) }}
    
    {{ form.submit }}
</form>

{% if success %}
<div style="color:green">
  Post data success:
  <p>{{ form.boolean.data }}</p>
  <p>{{ form.date.data }}</p>
  <p>{{ form.date_time.data }}</p>
  <p>{{ form.decimal.data }}</p>
  <p>{{ form.float.data }}</p>
  <p>{{ form.integer.data }}</p>
  <p>{{ form.radio.data }}</p>
  <p>{{ form.select.data }}</p>
  <p>{{ form.select_multiple.data }}</p>
  <p>{{ form.string.data }}</p>
  <p>{{ form.hidden.data }}</p>
  <p>{{ form.password.data }}</p>
  <p>{{ form.text_area.data }}</p>
  <p>HTML5 -------------------------</p>
  <p>{{ form.search.data }}</p>
  <p>{{ form.tel.data }}</p>
  <p>{{ form.url.data }}</p>
  <p>{{ form.email.data }}</p>
  <p>{{ form.html5_date_time.data }}</p>
  <p>{{ form.html5_date.data }}</p>
  <p>{{ form.time.data }}</p>
  <p>{{ form.date_time_local.data }}</p>
  <p>{{ form.html5_integer.data }}</p>
  <p>{{ form.html5_decimal.data }}</p>
  <p>{{ form.integer_range.data }}</p>
  <p>{{ form.decimal_range.data }}</p>
</div>
{% endif %}

app/templates/field/string.html
<form method="POST" action="{{ url_for('field_view.string') }}">
    {{ form.csrf_token }}
    {{ form.name.label }} {{ form.name(size=20) }}
    <input type="submit" value="Go">
</form>

{% if success %}
Post data:
<p>{{ form.name.data }}</p>
<p>{{ form.name.raw_data  }}</p>
<p>{{ form.name.name }}</p>
<p>{{ form.name.id }}</p>
<p>{{ form.name.type }}</p>
<p>{{ form.name.flags }}</p>
{% endif %}